### ISSUE TITLE
TODO for 0.2.0

### ISSUE THREAD

**Issue by erblast** [erblast/easyalluvial#8]
- [x] set seed in other tests
- [x] marginal histograms
- [x] categoric response
- [x] keep labels
- [x] optimize pdp performance, estimate
- [x] add training predictions
- [x] marginal histograms for long
- [x] add importance plot
- [x] parameter to change label size
- [x] refactor check_imp()
- [x] https://github.com/erblast/easyalluvial/issues/7

**Comment by erblast** [comment]
Pepare for release:
-[ ] check pdf manual rendering
-[ ] better defaults alluvial_model_response
-[ ] write blogpost about new features
-[ ] write alluvial model response tutorial
-[ ]  devtools::check()
-[ ]   devtools::check_win_devel()
-[ ]  rhub::check_for_cran()
-[ ]   rhub::check(platform = 'ubuntu-rchk')
-[ ]  rhub::check_with_sanitizers()
-[ ]   revdepcheck::revdep_check(num_workers = 4) (1 issue reported)
-[ ]  Polish NEWS

Submit to CRAN:
-[ ]   usethis::use_version()
-[ ]  Update cran-comments.md
-[ ]   devtools::submit_cran()
-[ ]   Approve email

Wait for CRAN...
-[ ]   Accepted 🎉
-[ ]   usethis::use_github_release()
-[ ]   usethis::use_dev_version()
-[¨] publish blogpost
-[ ] publish tutorial
